version: "3.7"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: example_database
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepassword
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=exampledb
    expose:
      - 3306
    ports:
      - "3308:3306"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:

